version: "3"

services:
    http:
        build:
            context: ./http
        volumes:
            - ../site/moodle:/var/www/html/moodle
            - ../data/moodledata:/var/www/moodledata
        ports:
            - "80:80"
        networks:
            - network
        links:
            - database
        depends_on:
            - database
    database:
        build:
                context: ./database
        volumes:
            - ../data/.data:/usr/src/data
            - ../data/.data:/var/lib/postgresql/data
        environment:
                POSTGRES_PASSWORD: root
        networks:
            - network
networks:
    network:
